FORMAT: 1A

# Companies [/reseller/companies]

## Company change theme [PUT]

+ Request (application/json)

            {
                "company":{
                    "theme": "black"
                }
            }

+ Response 200 (application/json)

            {
                "company":{
                    "name": "Foo Inc.",
                    "theme": "black"
                }
            }